[package]
name = "UefiProtocolDbLib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "uefi_protocol_db_lib"
path = "src/lib.rs"

[dependencies]
ahash = {workspace=true}
r-efi = {workspace=true}
spin = {workspace=true}
TplLock = {workspace=true}


[dependencies.uuid]
default-features = false
version = "1"